### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by baggepinnen** [baggepinnen/SignalAlignment.jl#1]
- [x] method for selecting master signal
- [ ] Align to barycenter
- [ ] Some plotting?
- [ ] More facilities for cropping / not cropping. Should there be a `postprocess` that takes in crop options?
- [ ] Handle `NaN/missing`
